### ISSUE TITLE
Force Screen Resize Not Working & Title Bar Display Icons Missing

### ISSUE THREAD

**Issue by markdwags** [msturgill/razor#8]
Building off the fork @jaedan has and just updated recently, everything works great except the Force Game Size and Title Bar Display icons are missing.  They counts are accurate, but the actual icons will not display. As for the Force Game Size, all the normal tricks don't work.

The build of Razor, 1.0.14.9, this feature works fine (which the source code doesn't exist).  I'm not sure why it wouldn't work on this build.  The UO client version is 5.0.8.3 and can be downloaded easily if needed.

**Comment by markdwags** [comment]
I did some digging around, comparing the working version of Razor I've been using (unfortunately the Crypt.cpp file from this build isn't available any place I can find) with 5.0.8.3, compared to the version I'm building and it looks like it's attempting to change the wrong location on the older client.

From what I can see, UO Client v5.0.8.3 and Razor v1.0.14, when you enter a new value into the Force Game Size boxes, 4 bytes are updated at address **6F0EC024** for X, **6F0EC028** for Y

After you hit Apply in the Options window in the game, the game window changes size and these 4 addresses are also then updated

- 006F83FC - For Y
- 006F83F0 - For X
- 006F83E4 - For Y
- 005BEAD8 - For X

I noticed @uoitalia is the only other person watching this project, perhaps they have some insights?

**Comment by uoitalia** [comment]
Give at least the client executable to inspect, it's something that has to do with the memory finder, so the client it's absolutely needed.

Maybe a link?

**Comment by markdwags** [comment]
Sure @uoitalia -- thank you.  If you want to download the full package, you can download it here:

http://www.uorenaissance.com/downloads/UO_Renaissance_Client_Full.exe

If you're just looking for the client.exe for this version, it is available here:

https://s3.amazonaws.com/quickuo/client.zip

**Comment by uoitalia** [comment]
I've tested the client in my virtual box, because after inspecting it the signatures were the same, everything works as expected (titlebar, resize screen)...Just recheck your modifications, to be sure that you haven't modified something that you shouldn't

**Comment by markdwags** [comment]
Interesting. I didn't change anything related to that functionality.  Except for adding a few comments to Crypt.cpp when I was debugging.  To confirm I didn't change something, I pulled down your fork, copied the whole Crypt project over, but I have the same issue.

I even took it a set further, just downloaded the razor.zip you generated with your fork that contains only the binaries as if I was just a normal user of UO, and it had the same issues (can't resize and missing icons)

I am running this on Windows 10, but I do run Razor in Admin mode.  This works fine with Razor 1.0.14.9. Are you testing in a VM running another Windows OS version?

Could it be related to the changes @jaedan made to fix the shared memory issues in his latest build and something with Windows 10?

If you run CheatEngine and monitor the same client.exe, but use 1.0.14.9 and use the builds we're producing here, you'll see they change different memory locations.

Thanks again @uoitalia

**Comment by uoitalia** [comment]
I think that you are forgetting something, because all that crypt.dll does is message handling and network hooking, plus some memory patching.

All the UI and Window functionality is done in C#, maybe the messages aren't correctly handled there.

My suggestion is, recheck everything, because from my side, binary release available on my github, the executable works as expected and draws everything on the screen plus the window resizing. And if your code doesn't even differ in the UI side, I really have no idea...just to tell something that you might find interesting, the drawings on the top window even work in ORION, if you modify the crypt to do the hooking neccessary for it (I've made it)

**Comment by uoitalia** [comment]
Anyway, to add to what you said, I've tested on two platforms, Win10 and W2016 Server (Plus the vBOX with windows 7 and windows XP, the solely platform where it won't work is XP, because I trashed the support for it)

**Comment by uoitalia** [comment]
hmmm, for the titlebar problem, maybe it does have to do with the enhanced graphic of the window GUI, some themes cause it, maybe this is something that should be resolved, and yes, I'm sure that my release is not perfect :P, that's because I'm using it in an installer, and the registry key are to be bound to the directory were the client is installed (and to tell the truth I don't allow server choise in my installations). Take in mind that this is something that should be done always in C#, as the client datapath are read from the register in there (this is something that has to do with ultima.dll and the datapath folder settings). And I have even an idea for the titlebar, maybe a research on the topic might help...

And for the rest this is of course a bad choise in the whole design, If my path is uncorrect the razor assistant should exit with an error message, not with a running execution (that has problems, since datafiles are not there).

Anyway, for the hang I noticed it too, it still depends on the datapath and some other sets not checked correctly, this is, as said before, because I'm not distributing it alone, it's inside an installer, as for the debug, it happens always because the json was removed and I had really no time to play with all the relative things, one way to solve would be to force, if you are distributing it in your server, at all the availability to choise default server, and only enter them by hand, and take only care of the user input.

**Comment by markdwags** [comment]
Your release is great, the bugs I'm referring to long existed before your build. I'm in no way criticizing that at all. 👍 

For the titlebar, its odd, two PCs, exact same version of UO.  On the one, they don't display with your build or mine.  On my other PC, they disable with no issues.

I'll have to do more digging on that, I'll get my changes committed to my repo soon.
